# Generated by Django 2.1.3 on 2018-11-21 11:29

import api.UserManager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('is_active', models.BooleanField(default=False, verbose_name='account active')),
                ('is_driver', models.BooleanField(default=False, verbose_name='driver status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin status')),
                ('dob', models.DateField()),
                ('address_1', models.CharField(max_length=60, verbose_name='address line 1')),
                ('address_2', models.CharField(max_length=60, verbose_name='address line 2')),
                ('address_3', models.CharField(max_length=60, verbose_name='address line 3')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
                ('county', models.CharField(max_length=60, verbose_name='county')),
                ('postcode', models.CharField(max_length=8, verbose_name='postcode')),
                ('drivers_licence_number', models.CharField(max_length=30)),
                ('taxi_licence_number', models.CharField(max_length=30)),
                ('driver_photo', models.ImageField(upload_to='')),
                ('date_joined', models.DateField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', api.UserManager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=50)),
                ('number_plate', models.CharField(max_length=10)),
                ('max_passengers', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('year_of_manufacture', models.DateField()),
                ('insurance_policy', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightnumber', models.CharField(max_length=10)),
                ('origin', models.CharField(max_length=100)),
                ('origin_terminal', models.CharField(max_length=5)),
                ('origin_IATA', models.CharField(max_length=5)),
                ('destination', models.CharField(max_length=100)),
                ('destination_terminal', models.CharField(max_length=5)),
                ('destination_IATA', models.CharField(max_length=5)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField()),
                ('direction', models.BooleanField()),
                ('distance', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('total', models.FloatField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Flight')),
            ],
        ),
    ]
