# Generated by Django 2.1.3 on 2018-11-21 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_update',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='address_1',
            field=models.CharField(blank=True, max_length=60, verbose_name='address line 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_2',
            field=models.CharField(blank=True, max_length=60, verbose_name='address line 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_3',
            field=models.CharField(blank=True, max_length=60, verbose_name='address line 3'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=60, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.CharField(blank=True, max_length=60, verbose_name='county'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='driver_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='drivers_licence_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.CharField(blank=True, max_length=8, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='taxi_licence_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
